const employeeReportData = [
  {
    id: 1,
    code: "NV001",
    name: "Nguyễn Văn A",
    department: "Kinh doanh",
    position: "Nhân viên bán hàng",
    workDays: 26,
    workHours: 208,
    overtime: 12,
    late: 2,
    absent: 0,
    salary: 12000000,
    performance: 95,
  },

  {
    id: 2,
    code: "NV002",
    name: "Trần Văn B",
    department: "Kho",
    position: "Nhân viên kho",
    workDays: 24,
    workHours: 192,
    overtime: 6,
    late: 1,
    absent: 1,
    salary: 10000000,
    performance: 88,
  },

  {
    id: 3,
    code: "NV003",
    name: "Lê Văn C",
    department: "Thu ngân",
    position: "Thu ngân",
    workDays: 27,
    workHours: 216,
    overtime: 15,
    late: 0,
    absent: 0,
    salary: 13500000,
    performance: 98,
  },

  {
    id: 4,
    code: "NV004",
    name: "Phạm Văn D",
    department: "Kế toán",
    position: "Kế toán",
    workDays: 25,
    workHours: 200,
    overtime: 4,
    late: 3,
    absent: 0,
    salary: 11000000,
    performance: 90,
  },

  {
    id: 5,
    code: "NV005",
    name: "Hoàng Thị E",
    department: "Nhân sự",
    position: "Chuyên viên HR",
    workDays: 26,
    workHours: 208,
    overtime: 8,
    late: 1,
    absent: 0,
    salary: 12500000,
    performance: 93,
  },
];

export default employeeReportData;