const stockTransferItemsData = [
  {
    id: 1,
    code: "HH000001",
    name: "Coca Cola",
    unit: "Lon",
    fromWarehouse: "Kho mặc định",
    fromLocation: "Kệ A1",
    toWarehouse: "Kho Quận 1",
    toLocation: "Kệ B2",
    quantity: 50,
  },
  {
    id: 2,
    code: "HH000002",
    name: "Pepsi",
    unit: "Lon",
    fromWarehouse: "Kho mặc định",
    fromLocation: "Kệ A2",
    toWarehouse: "Kho Quận 1",
    toLocation: "Kệ B3",
    quantity: 30,
  },
  {
    id: 3,
    code: "HH000003",
    name: "7Up",
    unit: "Lon",
    fromWarehouse: "Kho mặc định",
    fromLocation: "Kệ A3",
    toWarehouse: "Kho Quận 7",
    toLocation: "Kệ C1",
    quantity: 20,
  },
  {
    id: 1,
    code: "HH000001",
    name: "Coca Cola",
    unit: "Lon",
    fromWarehouse: "Kho mặc định",
    fromLocation: "Kệ A1",
    toWarehouse: "Kho Quận 1",
    toLocation: "Kệ B2",
    quantity: 50,
  },
  {
    id: 2,
    code: "HH000002",
    name: "Pepsi",
    unit: "Lon",
    fromWarehouse: "Kho mặc định",
    fromLocation: "Kệ A2",
    toWarehouse: "Kho Quận 1",
    toLocation: "Kệ B3",
    quantity: 30,
  },
  {
    id: 3,
    code: "HH000003",
    name: "7Up",
    unit: "Lon",
    fromWarehouse: "Kho mặc định",
    fromLocation: "Kệ A3",
    toWarehouse: "Kho Quận 7",
    toLocation: "Kệ C1",
    quantity: 20,
  },
  {
    id: 1,
    code: "HH000001",
    name: "Coca Cola",
    unit: "Lon",
    fromWarehouse: "Kho mặc định",
    fromLocation: "Kệ A1",
    toWarehouse: "Kho Quận 1",
    toLocation: "Kệ B2",
    quantity: 50,
  },
  {
    id: 2,
    code: "HH000002",
    name: "Pepsi",
    unit: "Lon",
    fromWarehouse: "Kho mặc định",
    fromLocation: "Kệ A2",
    toWarehouse: "Kho Quận 1",
    toLocation: "Kệ B3",
    quantity: 30,
  },
  {
    id: 3,
    code: "HH000003",
    name: "7Up",
    unit: "Lon",
    fromWarehouse: "Kho mặc định",
    fromLocation: "Kệ A3",
    toWarehouse: "Kho Quận 7",
    toLocation: "Kệ C1",
    quantity: 20,
  },
];

export default stockTransferItemsData;