// Dữ liệu mẫu cho màn hình danh sách phiếu nhập kho.
// Khi có API thật, chỉ cần thay nguồn import ở page danh sách.
const domesticVoucherType = "Mua hàng trong nước nhập kho chưa thanh toán";
const mainBranch = "CÔNG TY CỔ PHẦN GIÁO DỤC KHOA HỌC CÔNG NGHỆ";

export const stockInReceiptsData = [
  {
    id: 1,
    postedDate: "04/05/2026",
    voucherNo: "NK00375",
    description:
      "Mua hàng của CÔNG TY TNHH TECH GROCERY theo hóa đơn số 00004225",
    totalAmount: 11390000,
    deliverer: "",
    voucherType: domesticVoucherType,
    branch: mainBranch,
    details: [
      {
        id: 101,
        productCode: "MTINHBANG",
        productName:
          "Máy tính bảng hội nghị lớn (màn hình tương tác LED) cảm ứng 27 inch",
        warehouse: "Kho HH",
        warehouseAccount: "1561",
        payableAccount: "331",
        unit: "Cái",
        quantity: 1,
        unitPrice: 10546296,
        amount: 10546296,
        discountRate: 0,
        discountAmount: 0,
      },
    ],
  },
  {
    id: 2,
    postedDate: "04/02/2026",
    voucherNo: "NK00276",
    description:
      "Mua hàng của CÔNG TY TNHH THƯƠNG MẠI VÀ DỊCH VỤ KỸ THUẬT DIỆU PHÚC theo hóa đơn số 243015",
    totalAmount: 2340000,
    deliverer: "",
    voucherType: domesticVoucherType,
    branch: mainBranch,
    details: [
      {
        id: 201,
        productCode: "CAPHDMI",
        productName: "Cáp HDMI 4K dùng cho phòng học thông minh",
        warehouse: "Kho HH",
        warehouseAccount: "1561",
        payableAccount: "331",
        unit: "Sợi",
        quantity: 12,
        unitPrice: 195000,
        amount: 2340000,
        discountRate: 0,
        discountAmount: 0,
      },
    ],
  },
  {
    id: 3,
    postedDate: "02/02/2026",
    voucherNo: "NK00272",
    description:
      "Mua hàng của HỘ KINH DOANH CỬA HÀNG QUANG HẰNG theo hóa đơn số 72",
    totalAmount: 27578632,
    deliverer: "",
    voucherType: domesticVoucherType,
    branch: mainBranch,
    details: [
      {
        id: 301,
        productCode: "BANHOC01",
        productName: "Bàn học sinh chân sắt mặt gỗ chống xước",
        warehouse: "Kho HH",
        warehouseAccount: "1561",
        payableAccount: "331",
        unit: "Cái",
        quantity: 18,
        unitPrice: 875000,
        amount: 15750000,
        discountRate: 0,
        discountAmount: 0,
      },
      {
        id: 302,
        productCode: "GHEHOC01",
        productName: "Ghế học sinh tựa lưng nhựa đúc",
        warehouse: "Kho HH",
        warehouseAccount: "1561",
        payableAccount: "331",
        unit: "Cái",
        quantity: 24,
        unitPrice: 492860,
        amount: 11828632,
        discountRate: 0,
        discountAmount: 0,
      },
    ],
  },
  {
    id: 4,
    postedDate: "02/02/2026",
    voucherNo: "NK00271",
    description:
      "Mua hàng của HỘ KINH DOANH CỬA HÀNG QUANG HẰNG theo hóa đơn số 71",
    totalAmount: 15996750,
    deliverer: "",
    voucherType: domesticVoucherType,
    branch: mainBranch,
    details: [
      {
        id: 401,
        productCode: "TULOCKER",
        productName: "Tủ locker học sinh 18 ngăn sơn tĩnh điện",
        warehouse: "Kho HH",
        warehouseAccount: "1561",
        payableAccount: "331",
        unit: "Cái",
        quantity: 3,
        unitPrice: 5332250,
        amount: 15996750,
        discountRate: 0,
        discountAmount: 0,
      },
    ],
  },
  {
    id: 5,
    postedDate: "30/01/2026",
    voucherNo: "NK00275",
    description: "Mua hàng của CÔNG TY TNHH KIDO EDU theo hóa đơn số 00000010",
    totalAmount: 2870370,
    deliverer: "",
    voucherType: domesticVoucherType,
    branch: mainBranch,
    details: [
      {
        id: 501,
        productCode: "SOTAYGV",
        productName: "Sổ tay giáo viên bìa cứng khổ A5",
        warehouse: "Kho VPP",
        warehouseAccount: "1562",
        payableAccount: "331",
        unit: "Cuốn",
        quantity: 150,
        unitPrice: 19136,
        amount: 2870370,
        discountRate: 0,
        discountAmount: 0,
      },
    ],
  },
  {
    id: 6,
    postedDate: "30/01/2026",
    voucherNo: "NK00269",
    description: "Mua hàng của CÔNG TY TNHH CAO PHONG theo hóa đơn số 137810",
    totalAmount: 739815,
    deliverer: "",
    voucherType: domesticVoucherType,
    branch: mainBranch,
    details: [
      {
        id: 601,
        productCode: "BUTLONG",
        productName: "Bút lông bảng màu xanh",
        warehouse: "Kho VPP",
        warehouseAccount: "1562",
        payableAccount: "331",
        unit: "Hộp",
        quantity: 15,
        unitPrice: 49321,
        amount: 739815,
        discountRate: 0,
        discountAmount: 0,
      },
    ],
  },
  {
    id: 7,
    postedDate: "30/01/2026",
    voucherNo: "NK00267",
    description: "Mua hàng của CÔNG TY TNHH CAO PHONG theo hóa đơn số 136496",
    totalAmount: 3046296,
    deliverer: "",
    voucherType: domesticVoucherType,
    branch: mainBranch,
    details: [
      {
        id: 701,
        productCode: "GIAYPHOTO",
        productName: "Giấy photocopy A4 định lượng 70gsm",
        warehouse: "Kho VPP",
        warehouseAccount: "1562",
        payableAccount: "331",
        unit: "Ram",
        quantity: 48,
        unitPrice: 63465,
        amount: 3046296,
        discountRate: 0,
        discountAmount: 0,
      },
    ],
  },
  {
    id: 8,
    postedDate: "29/01/2026",
    voucherNo: "NK00277",
    description: "Mua hàng của CÔNG TY TNHH KIDO EDU theo hóa đơn số 00000001",
    totalAmount: 12020000,
    deliverer: "",
    voucherType: domesticVoucherType,
    branch: mainBranch,
    details: [
      {
        id: 801,
        productCode: "PROJECTOR",
        productName: "Máy chiếu lớp học độ sáng 4200 lumens",
        warehouse: "Kho HH",
        warehouseAccount: "1561",
        payableAccount: "331",
        unit: "Cái",
        quantity: 2,
        unitPrice: 6010000,
        amount: 12020000,
        discountRate: 0,
        discountAmount: 0,
      },
    ],
  },
  {
    id: 9,
    postedDate: "29/01/2026",
    voucherNo: "NK00266",
    description:
      "Mua hàng của CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ CONET theo hóa đơn số 507",
    totalAmount: 3800000,
    deliverer: "",
    voucherType: domesticVoucherType,
    branch: mainBranch,
    details: [
      {
        id: 901,
        productCode: "ROUTER01",
        productName: "Bộ phát wifi chuyên dụng cho lớp học",
        warehouse: "Kho HH",
        warehouseAccount: "1561",
        payableAccount: "331",
        unit: "Cái",
        quantity: 5,
        unitPrice: 760000,
        amount: 3800000,
        discountRate: 0,
        discountAmount: 0,
      },
    ],
  },
  {
    id: 10,
    postedDate: "29/01/2026",
    voucherNo: "NK00265",
    description:
      "Mua hàng của CÔNG TY TRÁCH NHIỆM HỮU HẠN SẢN XUẤT KINH DOANH THỰC PHẨM VÀ ĐỒ UỐNG WINBEE theo hóa đơn số 459",
    totalAmount: 24074074,
    deliverer: "",
    voucherType: domesticVoucherType,
    branch: mainBranch,
    details: [
      {
        id: 1001,
        productCode: "SUATUOI",
        productName: "Sữa tươi tiệt trùng hộp 180ml",
        warehouse: "Kho TP",
        warehouseAccount: "1563",
        payableAccount: "331",
        unit: "Thùng",
        quantity: 80,
        unitPrice: 300926,
        amount: 24074074,
        discountRate: 0,
        discountAmount: 0,
      },
    ],
  },
  {
    id: 11,
    postedDate: "28/01/2026",
    voucherNo: "NK00264",
    description:
      "Mua hàng của CÔNG TY TNHH THIẾT BỊ GIÁO DỤC AN PHÁT theo hóa đơn số 812",
    totalAmount: 18560000,
    deliverer: "Nguyễn Văn Bình",
    voucherType: domesticVoucherType,
    branch: mainBranch,
    details: [
      {
        id: 1101,
        productCode: "BANGTUONGTAC",
        productName: "Bảng tương tác thông minh 65 inch",
        warehouse: "Kho HH",
        warehouseAccount: "1561",
        payableAccount: "331",
        unit: "Cái",
        quantity: 1,
        unitPrice: 18560000,
        amount: 18560000,
        discountRate: 0,
        discountAmount: 0,
      },
    ],
  },
  {
    id: 12,
    postedDate: "27/01/2026",
    voucherNo: "NK00263",
    description:
      "Mua hàng của CÔNG TY TNHH VĂN PHÒNG PHẨM MINH LONG theo hóa đơn số 140",
    totalAmount: 9650000,
    deliverer: "",
    voucherType: domesticVoucherType,
    branch: mainBranch,
    details: [
      {
        id: 1201,
        productCode: "VPPSET",
        productName: "Bộ văn phòng phẩm dùng trong học kỳ mới",
        warehouse: "Kho VPP",
        warehouseAccount: "1562",
        payableAccount: "331",
        unit: "Bộ",
        quantity: 50,
        unitPrice: 193000,
        amount: 9650000,
        discountRate: 0,
        discountAmount: 0,
      },
    ],
  },
  {
    id: 13,
    postedDate: "26/01/2026",
    voucherNo: "NK00262",
    description:
      "Mua hàng của CÔNG TY CỔ PHẦN THIẾT BỊ TRƯỜNG HỌC SÀI GÒN theo hóa đơn số 055",
    totalAmount: 32450000,
    deliverer: "Trần Gia Huy",
    voucherType: domesticVoucherType,
    branch: mainBranch,
    details: [
      {
        id: 1301,
        productCode: "MAYIN01",
        productName: "Máy in laser đa chức năng",
        warehouse: "Kho HH",
        warehouseAccount: "1561",
        payableAccount: "331",
        unit: "Cái",
        quantity: 5,
        unitPrice: 6490000,
        amount: 32450000,
        discountRate: 0,
        discountAmount: 0,
      },
    ],
  },
  {
    id: 14,
    postedDate: "25/01/2026",
    voucherNo: "NK00261",
    description:
      "Mua hàng của CÔNG TY TNHH DỊCH VỤ TIN HỌC HẢI ĐĂNG theo hóa đơn số 778",
    totalAmount: 7280000,
    deliverer: "",
    voucherType: domesticVoucherType,
    branch: mainBranch,
    details: [
      {
        id: 1401,
        productCode: "MOUSEKEY",
        productName: "Bộ bàn phím và chuột không dây",
        warehouse: "Kho HH",
        warehouseAccount: "1561",
        payableAccount: "331",
        unit: "Bộ",
        quantity: 28,
        unitPrice: 260000,
        amount: 7280000,
        discountRate: 0,
        discountAmount: 0,
      },
    ],
  },
  {
    id: 15,
    postedDate: "24/01/2026",
    voucherNo: "NK00260",
    description:
      "Mua hàng của CÔNG TY TNHH CƠ KHÍ NỘI THẤT HÒA PHÁT theo hóa đơn số 902",
    totalAmount: 14325000,
    deliverer: "",
    voucherType: domesticVoucherType,
    branch: mainBranch,
    details: [
      {
        id: 1501,
        productCode: "GHEGV",
        productName: "Ghế giáo viên lưng lưới chân xoay",
        warehouse: "Kho HH",
        warehouseAccount: "1561",
        payableAccount: "331",
        unit: "Cái",
        quantity: 15,
        unitPrice: 955000,
        amount: 14325000,
        discountRate: 0,
        discountAmount: 0,
      },
    ],
  },
  {
    id: 16,
    postedDate: "23/01/2026",
    voucherNo: "NK00259",
    description:
      "Mua hàng của CÔNG TY CỔ PHẦN GIẢI PHÁP CÔNG NGHỆ ÁNH DƯƠNG theo hóa đơn số 321",
    totalAmount: 41600000,
    deliverer: "Phạm Quốc Thái",
    voucherType: domesticVoucherType,
    branch: mainBranch,
    details: [
      {
        id: 1601,
        productCode: "CAMERAIP",
        productName: "Camera IP lớp học kèm bộ lưu trữ",
        warehouse: "Kho HH",
        warehouseAccount: "1561",
        payableAccount: "331",
        unit: "Bộ",
        quantity: 8,
        unitPrice: 5200000,
        amount: 41600000,
        discountRate: 0,
        discountAmount: 0,
      },
    ],
  },
  {
    id: 17,
    postedDate: "22/01/2026",
    voucherNo: "NK00258",
    description:
      "Mua hàng của CÔNG TY TNHH DỊCH VỤ VẬN TẢI NAM AN theo hóa đơn số 189",
    totalAmount: 6875000,
    deliverer: "",
    voucherType: "Chi phí mua hàng phân bổ vào nhập kho",
    branch: mainBranch,
    details: [
      {
        id: 1701,
        productCode: "CPVC",
        productName: "Chi phí vận chuyển hàng nhập kho",
        warehouse: "Kho HH",
        warehouseAccount: "1561",
        payableAccount: "331",
        unit: "Lần",
        quantity: 1,
        unitPrice: 6875000,
        amount: 6875000,
        discountRate: 0,
        discountAmount: 0,
      },
    ],
  },
  {
    id: 18,
    postedDate: "21/01/2026",
    voucherNo: "NK00257",
    description:
      "Mua hàng của CÔNG TY TNHH THƯƠNG MẠI SÁNG TẠO theo hóa đơn số 011",
    totalAmount: 20512710,
    deliverer: "",
    voucherType: domesticVoucherType,
    branch: mainBranch,
    details: [
      {
        id: 1801,
        productCode: "TAINGHE",
        productName: "Tai nghe học ngoại ngữ có micro",
        warehouse: "Kho HH",
        warehouseAccount: "1561",
        payableAccount: "331",
        unit: "Cái",
        quantity: 30,
        unitPrice: 683757,
        amount: 20512710,
        discountRate: 0,
        discountAmount: 0,
      },
    ],
  },
  {
    id: 19,
    postedDate: "21/01/2026",
    voucherNo: "NK00257",
    description:
      "Mua hàng của CÔNG TY TNHH THƯƠNG MẠI SÁNG TẠO theo hóa đơn số 011",
    totalAmount: 20512710,
    deliverer: "",
    voucherType: domesticVoucherType,
    branch: mainBranch,
    details: [
      {
        id: 1801,
        productCode: "TAINGHE",
        productName: "Tai nghe học ngoại ngữ có micro",
        warehouse: "Kho HH",
        warehouseAccount: "1561",
        payableAccount: "331",
        unit: "Cái",
        quantity: 30,
        unitPrice: 683757,
        amount: 20512710,
        discountRate: 0,
        discountAmount: 0,
      },
    ],
  },
  {
    id: 20,
    postedDate: "21/01/2026",
    voucherNo: "NK00257",
    description:
      "Mua hàng của CÔNG TY TNHH THƯƠNG MẠI SÁNG TẠO theo hóa đơn số 011",
    totalAmount: 20512710,
    deliverer: "",
    voucherType: domesticVoucherType,
    branch: mainBranch,
    details: [
      {
        id: 1801,
        productCode: "TAINGHE",
        productName: "Tai nghe học ngoại ngữ có micro",
        warehouse: "Kho HH",
        warehouseAccount: "1561",
        payableAccount: "331",
        unit: "Cái",
        quantity: 30,
        unitPrice: 683757,
        amount: 20512710,
        discountRate: 0,
        discountAmount: 0,
      },
    ],
  },
];
