export const systemNotificationsData = [
  {
    id: "NOTI-001",
    type: "boarding-change",
    title: "Đổi món bán trú",
    message: "Lớp 3A đổi món trưa từ Cơm gà sốt nấm sang Cơm thịt kho trứng.",
    time: "10 phút trước",
    createdAt: "14/07/2026 13:50",
    isRead: false,
    priority: "high",
    parentName: "Nguyễn Thị Thu Hà",
    parentPhone: "0901 234 567",
    studentName: "Nguyễn Minh Anh",
    studentCode: "HS-3A-012",
    className: "3A",
    mealSession: "Bữa trưa",
    oldMeal: "Cơm gà sốt nấm",
    newMeal: "Cơm thịt kho trứng",
    amount: "0đ",
    status: "Chờ bếp xác nhận",
    content: "Phụ huynh yêu cầu đổi món bán trú do học sinh dị ứng nấm. Vui lòng cập nhật suất ăn trước 10:30.",
  },
  {
    id: "NOTI-002",
    type: "boarding-cancel",
    title: "Hủy món bán trú",
    message: "Phụ huynh Nguyễn Minh Anh đã hủy suất ăn chiều ngày hôm nay.",
    time: "25 phút trước",
    createdAt: "14/07/2026 13:35",
    isRead: false,
    priority: "medium",
    parentName: "Phạm Quốc Huy",
    parentPhone: "0918 456 789",
    studentName: "Phạm An Nhiên",
    studentCode: "HS-2B-021",
    className: "2B",
    mealSession: "Bữa chiều",
    oldMeal: "Sữa chua và bánh mì mềm",
    newMeal: "Đã hủy",
    amount: "35.000đ",
    status: "Đã ghi nhận hủy món",
    content: "Học sinh nghỉ học buổi chiều, phụ huynh yêu cầu hủy suất ăn và hoàn tiền vào ví thành viên.",
  },
  {
    id: "NOTI-003",
    type: "canteen-order",
    title: "Đặt món căn tin",
    message: "Có 12 đơn đặt món căn tin mới đang chờ xác nhận.",
    time: "45 phút trước",
    createdAt: "14/07/2026 13:15",
    isRead: false,
    priority: "high",
    parentName: "Trần Hoài Nam",
    parentPhone: "0933 222 111",
    studentName: "Trần Gia Bảo",
    studentCode: "HS-4C-006",
    className: "4C",
    mealSession: "Giờ ra chơi chiều",
    oldMeal: "",
    newMeal: "Bánh mì chà bông, Yaourt, Nước cam",
    amount: "62.000đ",
    status: "Chờ thu ngân xác nhận",
    content: "Phụ huynh đặt món căn tin cho học sinh. Vui lòng kiểm tra tồn kho và xác nhận đơn trước giờ ra chơi.",
  },
  {
    id: "NOTI-004",
    type: "wallet-topup",
    title: "Nạp tiền ví",
    message: "Tài khoản học sinh Trần Gia Bảo vừa được nạp 300.000đ.",
    time: "1 giờ trước",
    createdAt: "14/07/2026 12:55",
    isRead: true,
    priority: "low",
    parentName: "Lê Thanh Thảo",
    parentPhone: "0977 888 999",
    studentName: "Lê Minh Khang",
    studentCode: "HS-5A-018",
    className: "5A",
    mealSession: "Ví thành viên",
    oldMeal: "",
    newMeal: "",
    amount: "300.000đ",
    status: "Nạp tiền thành công",
    content: "Phụ huynh đã nạp tiền qua chuyển khoản. Số dư ví của học sinh đã được cập nhật để đặt món bán trú và căn tin.",
  },
  {
    id: "NOTI-005",
    type: "wallet-advance",
    title: "Ứng tiền",
    message: "Học sinh Lê Khánh Linh phát sinh yêu cầu ứng tiền 50.000đ tại căn tin.",
    time: "2 giờ trước",
    createdAt: "14/07/2026 12:05",
    isRead: false,
    priority: "medium",
    parentName: "Võ Minh Tâm",
    parentPhone: "0986 555 333",
    studentName: "Võ Khánh Linh",
    studentCode: "HS-1C-009",
    className: "1C",
    mealSession: "Căn tin",
    oldMeal: "",
    newMeal: "Sữa hộp, bánh bông lan",
    amount: "50.000đ",
    status: "Chờ phụ huynh duyệt ứng tiền",
    content: "Ví học sinh không đủ số dư khi mua món tại căn tin. Hệ thống đã tạo yêu cầu ứng tiền gửi đến phụ huynh.",
  },
];
